# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-FormBuilder
version:      0.05
version_from: lib/Text/FormBuilder.pm
installdirs:  site
requires:
    CGI::FormBuilder:              2.13
    Text::Template:                1.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
