--- #YAML:1.0
name:                Text-FormBuilder
version:             0.13
abstract:            Create CGI::FormBuilder objects from simple text descriptions
license:             ~
author:              
    - Peter Eichman <peichman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI::FormBuilder:              3
    Class::Base:                   0.03
    Parse::RecDescent:             1.94
    Text::Template:                1.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
